### ISSUE TITLE
OverflowError when executing `make gui` in DATA

### ISSUE THREAD

**Issue by romen** [IAIK/data-gui#2]
Hi,

I was testing the DATA framework on my machine inside a clean ubuntu:xenial installation in a container.

Everything else seems to work regarding the analysis, but running `make gui` delivers this `OverflowError` that I don't know how to debug.

Also, to have this working I was required to install extra packages that were not mentioned in the main `README` for DATA:
- a libgl driver (in my case `nvidia-current`)
- `libxkbcommon-x11-0`

```
ubuntu@DATA:~/repos/DATA$ make gui
[openssl]Testing 'des-ecb 64'
[openssl/des-ecb]Exporting framework files
[openssl/des-ecb]Exporting completed.
[openssl/des-ecb]Testing 'des-ecb 64' completed in 0.02 seconds (or 0.03 CPU seconds) with a peak RAM usage of 146.82 MiB
============================================================
Export generated: cryptolib/openssl/lastresults/openssl/des-ecb/framework.zip

Traceback (most recent call last):
  File "/home/ubuntu/repos/DATA/analysis/.pyenv/bin/datagui", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ubuntu/repos/DATA/data-gui/bin/datagui", line 4, in <module>
    main()
  File "/home/ubuntu/repos/DATA/data-gui/datagui/main.py", line 28, in main
    MainWindow()
  File "/home/ubuntu/repos/DATA/data-gui/datagui/package/ui/MainWindow.py", line 120, in __init__
    self.setupInfoMap(lib_hierarchy)
  File "/home/ubuntu/repos/DATA/data-gui/datagui/package/ui/MainWindow.py", line 385, in setupInfoMap
    asm_line_text.find(search_str), len(search_str) - 1)
  File "/home/ubuntu/repos/DATA/data-gui/datagui/package/ui/MainWindow.py", line 646, in setAsmIndicator
    asm_editor.SendScintilla(QsciScintilla.SCI_SETINDICATORVALUE, value)
OverflowError: argument 2 overflowed: value must be in the range 0 to 18446744073709551615
```

**Comment by sam1013** [comment]
Fixed.
